idam:
  api:
    url: http://localhost:${wiremock.server.port:5000}
  s2s-auth:
    url: http://localhost:${wiremock.server.port:5000}/s2s

spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:${wiremock.server.port:5000}/o

azure:
  application-insights:
    web:
      enabled: false

documentStoreUrl: http://localhost:${wiremock.server.port:4506}
caseDataStoreUrl: http://localhost:${wiremock.server.port:4452}
