java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    CCD_DATA_STORE_API_BASE_URL: http://ccd-data-store-api-pr-1400.service.core-compute-preview.internal
