asp_name = "ccd-case-document-am-api-aat"
asp_rg = "ccd-case-document-am-api-aat"
idam_api_url = "https://idam-api.aat.platform.hmcts.net"
document_management_valid_domain = "^https?://(?:api-gateway\\.preprod\\.dm\\.reform\\.hmcts\\.net|dm-store-aat\\.service\\.core-compute-aat\\.internal(?::\\d+)?)"
capacity = "4"
